# Generated by Django 2.1.5 on 2019-01-07 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_auto_20190108_0105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='end',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='education',
            name='pass_year',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='education',
            name='start',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='info',
            name='dob',
            field=models.DateField(verbose_name='Date of Birth'),
        ),
        migrations.AlterField(
            model_name='training',
            name='end',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='training',
            name='start',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='work',
            name='end',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='work',
            name='start',
            field=models.IntegerField(),
        ),
    ]
