# Generated by Django 2.1.5 on 2019-01-07 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0004_auto_20190108_0116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='end',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='education',
            name='pass_year',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='training',
            name='end',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='training',
            name='pass_year',
            field=models.TimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='work',
            name='contract_year',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='work',
            name='end',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
