# Generated by Django 2.1.5 on 2019-01-07 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0005_auto_20190108_0119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='description',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
