# Generated by Django 2.1.5 on 2019-01-07 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0010_auto_20190108_0207'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='language_and_framework',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
    ]
