# Generated by Django 2.1.5 on 2019-01-18 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0013_project_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='fact',
            name='details',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='fact',
            name='icon',
            field=models.CharField(default='', max_length=100),
        ),
    ]
