# Generated by Django 2.1.5 on 2019-01-07 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0003_auto_20190108_0112'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='contract_year',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='education',
            name='end',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='education',
            name='pass_year',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='training',
            name='end',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='training',
            name='pass_year',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='work',
            name='end',
            field=models.IntegerField(null=True),
        ),
    ]
