# Generated by Django 2.1.5 on 2019-01-07 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0006_auto_20190108_0120'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='education',
            options={'ordering': ['end']},
        ),
    ]
