# Generated by Django 2.1.5 on 2019-01-07 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0009_social_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='about',
            field=models.TextField(max_length=1000),
        ),
    ]
