# Generated by Django 2.1.5 on 2019-01-07 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0012_auto_20190108_0216'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
