# Generated by Django 2.1.5 on 2019-02-05 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='language_and_framework',
        ),
    ]
