# Generated by Django 2.1.5 on 2019-02-05 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_remove_project_language_and_framework'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project_feature',
            name='project',
        ),
        migrations.RemoveField(
            model_name='project_tag',
            name='project',
        ),
        migrations.AddField(
            model_name='project',
            name='feature',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='portfolio.Project_Feature'),
        ),
        migrations.AddField(
            model_name='project',
            name='tag',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='portfolio.Project_Tag'),
        ),
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='portfolio.Project_Category'),
        ),
    ]
